Clean up test script for dummy happy path
Checking for a 200 HTTP status against the server root will be
successful, as per Nginx's default config.

diff --git a/nginx-helm/nginx/templates/test-health.yaml b/nginx-helm/nginx/templates/test-health.yaml
--- a/nginx-helm/nginx/templates/test-health.yaml
+++ b/nginx-helm/nginx/templates/test-health.yaml
@@ -18,11 +18,11 @@ spec:
       set -e
       echo "Testing nginx health..."
       
-      out="$(curl nginx-service.default.svc.cluster.local:8080/healthz)"
-      if [ "${out#404}" = "$out" ]; then
-        echo "ERROR: Could not retrieve health response"
-        exit 1
-      else
+      curl -v nginx-service.default.svc.cluster.local:8080 2>&1 | grep '200 OK'
+      if [ $? -eq  0 ]; then
         echo "✓ Application reports healthy status"
         exit 0
+      else
+        echo "ERROR: Application is unhealthy!"
+        exit 1
       fi
